[package]
name = "rust_grapher"
version = "0.1.0"
authors = ["Severn Everett <severn.everett@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
